export const countryData = {
	1: [
		"Bahrain",
		"Iran",
		"Iraq",
		"Israel",
		"Jordan",
		"Kuwait",
		"Lebanon",
		"Oman",
		"Qatar",
		"Saudi Arabia",
		"Palestine",
		"Syria",
		"United Arab Emirates",
		"Yemen",
	],
	2: ["Algeria", "Egypt", "Libya", "Morocco", "Sudan", "Tunisia"],
	3: [],
	4: [
		"Russia",
		"Ukraine",
		"Ukraine",
		"Poland",
		"Ukraine",
		"Poland",
		"Romania",
		"Czech Republic (Czechia)",
		"Hungary",
		"Belarus",
		"Bulgaria",
		"Moldova",
		"Slovakia",
		"Germany",
		"Germany",
		"Netherlands",
		"Belgium",
		"France",
		"Austria",
		"Switzerland",
		"Luxembourg",
		"Monaco",
		"Liechtenstein",
		"United Kingdom",
	],
	5: [
		"China",
		"India",
		"Japan",
		"Pakistan",
		"Bangladesh",
		"Vietnam",
		"Philippines",
		"Thailand",
		"Myanmar",
		"South Korea",
		"Malaysia",
		"Indonesia",
		"North Korea",
		"Mongolia",
		"Nepal",
		"Cambodia",
		"Sri Lanka",
		"Laos",
		"Taiwan",
		"Singapore",
		"Afghanistan",
		"Armenia",
		"Azerbaijan",
		"Bahrain",
		"Bhutan",
		"Brunei",
		"Cyprus",
		"Georgia",
		"Kazakhstan",
		"Kyrgyzstan",
		"Iran",
		"Iraq",
		"Israel,",
		"Jordan,",
		"Kuwait,",
		"Laos,",
		"Lebanon,",
		"Macau,",
		"Maldives",
		"Mongolia,",
		"Oman,",
		"Palestine,",
		"Philippines,",
		"Qatar",
		"Saudi Arabia",
		"Singapore,",
		"South Korea,",
		"Sri Lanka,",
		"Syria,",
		"Tajikistan,",
		"Thailand,",
		"Timor Leste,",
		"Turkey,",
		"Turkmenistan,",
		"United Arab Emirates,",
		"Uzbekistan,",
		"Vietnam,",
		"Yemen",
	],
	6: [
		"New Zealand",
		"Australia",
		"Australia",
		"Fiji",
		"Kiribati",
		"Marshall Islands",
		"Papua New Guinea",
		"Vanuatu",
		"Solomon Islands",
		"Palau",
		"Tonga",
		"Tuvalu",
		"Micronesia",
		"Samoa",
		"New Zealand",
		"Australia",
		"Australia",
		"Fiji",
		"Kiribati",
		"Marshall Islands",
		"Papua New Guinea",
		"Vanuatu",
		"Solomon Islands",
		"Palau",
		"Tonga",
		"Tuvalu",
		"Micronesia",
		"Samoa",
	],
	7: [
		"Jamaica",
		"Barbados",
		"Barbados",
		"Dominican Republic",
		"Barbados",
		"Dominican Republic",
		"Saint Lucia",
		"Grenada",
		"Dominica",
		"Antigua and Barbuda",
		"The Bahamas",
		"Trinidad and Tobago",
		"Saint Vincent and the Grenadines",
		"Saint Kitts and Nevis",
		"Haiti",
		"Cuba",
		"Montserrat",
		"U.S. Virgin Islands",
		"Turks and Caicos Islands",
		"Anguilla",
		"Belize",
		"Puerto Rico",
		"Suriname",
		"Guyana",
	],
	8: [
		"Antigua and Barbuda",
		"Bahamas",
		"Bahamas",
		"Barbados",
		"Belize",
		"Canada",
		"Costa Rica",
		"Cuba",
		"Dominica",
		"Dominican Republic",
		"El Salvador",
		"Grenada",
		"Guatemala",
		"Haiti",
		"Honduras",
		"Jamaica",
		"Mexico",
		"Nicaragua",
		"Panama",
		"Saint Kitts and Nevis",
		"Saint Lucia",
		"Saint Vincent and the Grenadines",
		"Trinidad and Tobago",
		"United States",
	],
};
