export const RegionData = {
	1: [
		{
			1: [
				"United Kingdom",
				"Sweden",
				"Iceland",
				"Denmark",
				"Finland",
				"Ireland",
				"Norway",
				"Lithuania",
				"Latvia",
				"Estonia",
			],
			2: [
				"Russia",
				"Ukraine",
				"Poland",
				"Romania",
				"Czech Republic (Czechia)",
				"Hungary",
				"Belarus",
				"Bulgaria",
				"Moldova",
				"Slovakia",
			],
			3: [
				"Germany",
				"Netherlands",
				"Belgium",
				"France",
				"Austria",
				"Switzerland",
				"Luxembourg",
				"Monaco",
				"Liechtenstein",
			],
			4: [
				"Italy",
				"Spain",
				"Greece",
				"Portugal",
				"Serbia",
				"Croatia",
				"Bosnia and Herzegovina",
				"Albania",
				"North Macedonia",
				"Slovenia",
				"Montenegro",
				"Malta",
				"Andorra",
				"San Marino",
				"Holy See",
			],
		},
	],
	2: [
		{
			1: [
				"United Kingdom",
				"Sweden",
				"Iceland",
				"Denmark",
				"Finland",
				"Ireland",
				"Norway",
				"Lithuania",
				"Latvia",
				"Estonia",
			],
			2: [
				"Russia",
				"Ukraine",
				"Poland",
				"Romania",
				"Czech Republic (Czechia)",
				"Hungary",
				"Belarus",
				"Bulgaria",
				"Moldova",
				"Slovakia",
			],
			3: [
				"Germany",
				"Netherlands",
				"Belgium",
				"France",
				"Austria",
				"Switzerland",
				"Luxembourg",
				"Monaco",
				"Liechtenstein",
			],
			4: [
				"Italy",
				"Spain",
				"Greece",
				"Portugal",
				"Serbia",
				"Croatia",
				"Bosnia and Herzegovina",
				"Albania",
				"North Macedonia",
				"Slovenia",
				"Montenegro",
				"Malta",
				"Andorra",
				"San Marino",
				"Holy See",
			],
		},
	],
	3: [],
};
